name: Weekly Deep Check

on:
  schedule:
    # Every Sunday at 6:00 AM Jerusalem time (UTC+2/+3)
    # During standard time (UTC+2): 4:00 AM UTC
    # During daylight time (UTC+3): 3:00 AM UTC
    # Using 3:00 AM UTC to cover both cases
    - cron: '0 3 * * 0'
  workflow_dispatch: # Allow manual trigger

jobs:
  deep-check:
    name: Deep Code Quality Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Enable Corepack
        run: corepack enable

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: latest

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Generate Prisma Client
        run: npx prisma generate

      - name: Run deep check
        run: npm run deep-check

      - name: Create Issue on Failure
        if: failure()
        uses: actions/github-script@v7
        with:
          script: |
            const title = `Weekly Deep Check Failed - ${new Date().toISOString().split('T')[0]}`;
            const body = `
            ## Weekly Deep Check Failed 🚨

            The weekly deep check has failed. Please review the following:

            - **Date**: ${new Date().toISOString()}
            - **Workflow**: ${{ github.workflow }}
            - **Run ID**: ${{ github.run_id }}

            ### Actions Required:
            1. Check the workflow logs for specific errors
            2. Fix any ESLint/TypeScript issues
            3. Ensure all tests are passing
            4. Verify code formatting

            ### Quick Links:
            - [Workflow Run](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})
            - [Repository](${{ github.server_url }}/${{ github.repository }})

            This issue was automatically created by the weekly deep check workflow.
            `;

            github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: title,
              body: body,
              labels: ['bug', 'automated', 'weekly-check']
            });

      - name: Comment on Success
        if: success()
        uses: actions/github-script@v7
        with:
          script: |
            console.log('✅ Weekly deep check passed successfully!');
            console.log('All code quality checks are passing.');
